config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :show, :create]
  resource :session, only: [:create, :new, :destroy]

  resources :bands

  resources :albums, only: [:new, :create, :edit, :show, :update, :destroy] do
    resources :track, only: [:new]
  end
  resources :tracks, only: [:new, :create, :edit, :show, :update, :destroy] do
    resources :albums, only: [:new]
  end


   root to: redirect("/users")
end

app/models/album.rb
class Album < ActiveRecord::Base

  belongs_to :band

  has_many :tracks,
  dependent: :destroy
end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :albums,
  dependent: :destroy

  has_many :tracks,
  through: :albums,
  source: :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
end

app/models/user.rb
require 'SecureRandom'
require 'BCrypt'

class User < ActiveRecord::Base
  attr_reader :password

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true
  after_initialize :ensure_session_token

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User::generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User::generate_session_token
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

  private
  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def user_logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    session[:session_token] = current_user.session_token
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def show
    @band = Band.find(params[:id])

    render :show
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by(params[:email], params[:password])

    if user.nil?
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    else
      log_in_user!(user)
      redirect_to user_url(current_user)
    end
  end

  def destroy
    user_logout!
    redirect_to new_session_url
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_token
    token = <<-HTML
      <input
      type="hidden"
      name="authenticity_token"
      value="#{form_authenticity_token}">
    HTML

    token.html_safe
  end

end

app/views/bands/show.html.erb
<h1>Welcome <%=@band.name%>!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Musicapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user.nil? %>
  <%= link_to "Sign in", new_session_url %> or
  <%= link_to "Sign up", new_user_url %>
<% else %>
  <%= current_user.email %>
  <%= button_to "Logout", session_url, method: :delete %>
<% end %>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1> Let's create a new user! </h1>

<%= render 'shared/errors' %>

<form action="/users" method="post">

  <%=form_token%>

  <label>Email :</label>
  <br>
  <input type="text" name="user[email]" value="<%=@user.email%>">
  <br>
  <label>Password :</label>
  <br>
  <input type="password" name="user[password]">

  <br>
  <br>

  <input type='submit' value="Create!">
</form>

app/views/users/show.html.erb
<h1>Welcome <%=@user.email%>!</h1>